# Generated by Django 4.2.6 on 2023-11-18 06:59

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game_engine.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Building', editable=False, max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('base_resource_costs', models.JSONField(default=dict)),
                ('upgrade_duration', models.DurationField(default=datetime.timedelta(seconds=5))),
                ('dynamic_resource_costs', models.JSONField(default=dict)),
                ('dynamic_upgrade_duration', models.DurationField(default=datetime.timedelta(seconds=5))),
                ('arithmetic_population', models.PositiveSmallIntegerField(default=0)),
                ('hp', models.PositiveSmallIntegerField(default=100)),
                ('upgrade_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upgrade_start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Classical', 'Classical'), ('Rapid', 'Rapid')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('galaxy', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('planet_number', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(default=game_engine.models.generate_random_name, max_length=50)),
                ('id', models.CharField(default='', editable=False, max_length=12, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['galaxy', 'planet_number'],
                'unique_together': {('galaxy', 'planet_number')},
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('troops', models.JSONField(default=dict)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='game_engine.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('troops', models.JSONField(default=dict)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='army', to='game_engine.planet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orion_credits', models.PositiveIntegerField(default=1000)),
                ('population', models.PositiveIntegerField(default=0)),
                ('attack_points', models.PositiveIntegerField(default=0)),
                ('defense_points', models.PositiveIntegerField(default=0)),
                ('raiding_points', models.PositiveIntegerField(default=0)),
                ('player_class_choices', models.JSONField(default=dict)),
                ('player_class', models.CharField(blank=True, default='class1', max_length=50, null=True)),
                ('special_troops', models.JSONField(default=dict)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='game_engine.gamemode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_mode')},
            },
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_engine.building')),
                ('stored_resources', models.JSONField(default=dict)),
                ('max_capacity', models.PositiveIntegerField(default=20000)),
                ('building_type', models.CharField(default='Silo', max_length=10)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silo', to='game_engine.planet')),
            ],
            bases=('game_engine.building',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_engine.building')),
                ('base_range', models.IntegerField(default=1)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='game_engine.planet')),
            ],
            bases=('game_engine.building',),
        ),
        migrations.CreateModel(
            name='Forge',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_engine.building')),
                ('army', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forge', to='game_engine.army')),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forge', to='game_engine.planet')),
            ],
            bases=('game_engine.building',),
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_engine.building')),
                ('generated_resources', models.PositiveIntegerField(default=0)),
                ('production_rate_per_sec', models.PositiveIntegerField(default=1)),
                ('resource_type', models.CharField(choices=[('Boron', 'Boron'), ('Oxygen', 'Oxygen'), ('Uranium', 'Uranium'), ('Helium', 'Helium')], max_length=10)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mine', to='game_engine.planet')),
            ],
            options={
                'unique_together': {('planet', 'resource_type')},
            },
            bases=('game_engine.building',),
        ),
    ]
