# Generated by Django 4.2.6 on 2023-11-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='game_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_engine.gamemode'),
        ),
    ]
